[application]
    name = "ECTE"
    user = "ecte"

[bash]
    mkdir = "/bin/mkdir"
    useradd = "/usr/sbin/useradd"
    usermod = "/usr/sbin/usermod"
    userdel = "/usr/sbin/userdel"
    groupadd = "/usr/sbin/groupadd"
    groupdel = "/usr/sbin/groupdel"
    echo = "/bin/echo"
    rm = "/bin/rm"
